export default [
  {
    name: "Огурцы",
    category: "Овощи",
    price: 239.9,
    discount: 60,
    rating: [4, 5, 3, 5],
    isFavorite: true,
    img: "img/cucumber.jpg",
    id: "p1",
    inCart: false,
  },
  {
    name: "Лук репчатый",
    category: "Овощи",
    price: 54.9,
    discount: 0,
    rating: [5, 1, 2],
    isFavorite: false,
    img: "img/onion.jpg",
    id: "p2",
    inCart: false,
  },
  {
    name: "Шампиньоны",
    category: "Грибы",
    price: 239.9,
    discount: 0,
    rating: [3, 2, 1],
    isFavorite: true,
    img: "img/champignons.jpg",
    id: "p3",
    inCart: false,
  },
  {
    name: "Апельсины",
    category: "Фрукты",
    price: 94.9,
    discount: 0,
    rating: [5, 4, 5],
    isFavorite: true,
    img: "img/oranges.jpg",
    id: "p4",
    inCart: false,
  },
  {
    name: "Нектарины",
    category: "Фрукты",
    price: 249.9,
    discount: 20,
    rating: [5, 5, 4],
    isFavorite: true,
    img: "img/nectarines.jpg",
    id: "p5",
    inCart: true,
  },
  {
    name: "Помидоры",
    category: "Овощи",
    price: 169.9,
    discount: 0,
    rating: [5, 5, 5],
    isFavorite: true,
    img: "img/tomatoes.jpg",
    id: "p6",
    inCart: false,
  },
];
